# Numpy基本操作

## 三个重要属性

a.type, a.shape, a.ndim

In [1]:
import numpy as np

In [6]:
a =np.array([12,10])
a.dtype

dtype('int32')

In [7]:
a = np.float32([1,12])
a.dtype

dtype('float32')

In [9]:
a = np.float32([[2,2],[1,3]])
a.dtype

dtype('float32')

In [10]:
print(a.shape)

(2, 2)


In [11]:
print(a.ndim)

2


## 创建矩阵

In [12]:
a = np.array([[1,2],[3,2]])
print(a)

[[1 2]
 [3 2]]


In [15]:
a = np.arange(1, 10, 2)
print(a)

[1 3 5 7 9]


In [16]:
a = np.linspace(1, 50, 10)
a

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [17]:
a = np.zeros((3,3))
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [19]:
a = np.ones((3,4))
a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [24]:
a = np.eye(4,3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [23]:
a = np.identity(6)
a


array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [26]:
a = np.random.randint(0, 10, 2)
a

array([5, 6])

# 矩阵转换

In [29]:
a = np.array([[1,2,3],[3,4,5]])
a.shape

(2, 3)

In [31]:
a.reshape((3,2))
a

array([[1, 2],
       [3, 3],
       [4, 5]])

In [32]:
a = np.reshape(a, (3,2))

In [33]:
a

array([[1, 2],
       [3, 3],
       [4, 5]])

In [34]:
a.flatten()

array([1, 2, 3, 3, 4, 5])

In [35]:
a.ravel()

array([1, 2, 3, 3, 4, 5])

In [37]:
a.shape

(3, 2)

In [38]:
a.T

array([[1, 3, 4],
       [2, 3, 5]])

In [39]:
a.transpose()

array([[1, 3, 4],
       [2, 3, 5]])

In [40]:
a

array([[1, 2],
       [3, 3],
       [4, 5]])

In [41]:
a= a.T
b= np.ones_like(a)

In [42]:
b

array([[1, 1, 1],
       [1, 1, 1]])

In [43]:
np.hstack((a,b))

array([[1, 3, 4, 1, 1, 1],
       [2, 3, 5, 1, 1, 1]])

In [44]:
np.vstack((a,b))

array([[1, 3, 4],
       [2, 3, 5],
       [1, 1, 1],
       [1, 1, 1]])

# 最大值，最小值，均值

In [46]:
np.max(a)

5

In [47]:
a.max()

5

In [48]:
a.max(axis=1)

array([4, 5])

In [49]:
a.min(axis=0)

array([1, 3, 4])

In [50]:
a.mean()

3.0

In [51]:
a.mean(axis=1)

array([2.66666667, 3.33333333])

In [52]:
a.mean(axis=0)

array([1.5, 3. , 4.5])

# 矩阵运算

In [3]:
x = np.array([1,2,4])
y = np.array([2,3,4])
print(x.shape, y.shape)

(3,) (3,)


对应元素相乘

In [4]:
print(x*y)

[ 2  6 16]


矩阵相乘

In [5]:
print(x@y.T)

24


点乘

In [6]:
print(x.dot(y))

24


In [7]:
print(x,y)

[1 2 4] [2 3 4]


In [9]:
np.dot?

Docstring:
dot(a, b, out=None)

Dot product of two arrays. Specifically,

- If both `a` and `b` are 1-D arrays, it is inner product of vectors
  (without complex conjugation).

- If both `a` and `b` are 2-D arrays, it is matrix multiplication,
  but using :func:`matmul` or ``a @ b`` is preferred.

- If either `a` or `b` is 0-D (scalar), it is equivalent to :func:`multiply`
  and using ``numpy.multiply(a, b)`` or ``a * b`` is preferred.

- If `a` is an N-D array and `b` is a 1-D array, it is a sum product over
  the last axis of `a` and `b`.

- If `a` is an N-D array and `b` is an M-D array (where ``M>=2``), it is a
  sum product over the last axis of `a` and the second-to-last axis of `b`::

    dot(a, b)[i,j,k,m] = sum(a[i,j,:] * b[k,:,m])

Parameters
----------
a : array_like
    First argument.
b : array_like
    Second argument.
out : ndarray, optional
    Output argument. This must have the exact kind that would be returned
    if it was not used. In particular, it must have the r

# 元素获取

In [5]:
a = np.random.randint(1, 20, 10)
a

array([10,  5, 11, 17, 17,  4, 13,  7, 11,  3])

## 获得某行或者列数据

**小标从0开始**

In [13]:
a= np.random.randint(1,50,(3,4))
a

array([[39, 49, 49, 41],
       [29, 26, 27, 19],
       [15, 31, 49, 20]])

In [16]:
a[:,0]

array([39, 29, 15])

In [14]:
a[0]

array([39, 49, 49, 41])

## 获得某个坐标上的元素

从0开始计数，不能取到最后的索引

In [7]:
print('a.shape:{}'.format(a.shape))
a[2]

a.shape:(10,)


11

In [9]:
a= np.random.random((5,3))
a

array([[0.80525568, 0.94498176, 0.08013137],
       [0.12909301, 0.714324  , 0.81139411],
       [0.60635914, 0.79340979, 0.60064226],
       [0.68203631, 0.90533178, 0.0660352 ],
       [0.09469555, 0.95750311, 0.61696103]])

## get the data in one region

In [11]:
a[:2, :2]
print(a[1:3,1:3])

[[0.714324   0.81139411]
 [0.79340979 0.60064226]]


## 元素赋值

In [17]:
a[0,0]=100
a

array([[100,  49,  49,  41],
       [ 29,  26,  27,  19],
       [ 15,  31,  49,  20]])

In [20]:
b=[1,1,1,1]
a[0]=b
a

array([[ 1,  1,  1,  1],
       [29, 26, 27, 19],
       [15, 31, 49, 20]])